# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 241, 381))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_1.setGeometry(QtCore.QRect(10, 20, 87, 20))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 60, 87, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 80, 87, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 100, 87, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 120, 87, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(10, 140, 87, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 160, 87, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 180, 87, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 200, 87, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 220, 87, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 240, 87, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 260, 87, 20))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 280, 87, 20))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 300, 87, 20))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 320, 87, 20))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_17.setGeometry(QtCore.QRect(130, 20, 87, 20))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_18.setGeometry(QtCore.QRect(130, 40, 87, 20))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_19.setGeometry(QtCore.QRect(130, 60, 87, 20))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_20.setGeometry(QtCore.QRect(130, 80, 87, 20))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_21.setGeometry(QtCore.QRect(130, 100, 87, 20))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_22.setGeometry(QtCore.QRect(130, 120, 87, 20))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_23.setGeometry(QtCore.QRect(130, 140, 87, 20))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_24.setGeometry(QtCore.QRect(130, 160, 87, 20))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_25.setGeometry(QtCore.QRect(130, 180, 87, 20))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_26.setGeometry(QtCore.QRect(130, 200, 87, 20))
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_27.setGeometry(QtCore.QRect(130, 220, 87, 20))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_28.setGeometry(QtCore.QRect(130, 240, 87, 20))
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_29.setGeometry(QtCore.QRect(130, 260, 87, 20))
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_30.setGeometry(QtCore.QRect(130, 280, 87, 20))
        self.checkBox_30.setObjectName("checkBox_30")
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_31.setGeometry(QtCore.QRect(130, 300, 87, 20))
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_32.setGeometry(QtCore.QRect(130, 320, 87, 20))
        self.checkBox_32.setObjectName("checkBox_32")
        self.btnSelectAll = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectAll.setGeometry(QtCore.QRect(0, 340, 113, 32))
        self.btnSelectAll.setObjectName("btnSelectAll")
        self.btnSelectNone = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectNone.setGeometry(QtCore.QRect(120, 340, 113, 32))
        self.btnSelectNone.setObjectName("btnSelectNone")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.groupBox_2.setObjectName("groupBox_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 700, 480))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 478))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnSetTimeSeriesPlot = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSetTimeSeriesPlot.setGeometry(QtCore.QRect(100, 0, 161, 32))
        self.btnSetTimeSeriesPlot.setObjectName("btnSetTimeSeriesPlot")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(710, 0, 300, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.rbDataFromFile = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbDataFromFile.setGeometry(QtCore.QRect(0, 20, 131, 20))
        self.rbDataFromFile.setObjectName("rbDataFromFile")
        self.rbRealTimeData = QtWidgets.QRadioButton(self.groupBox_3)
        self.rbRealTimeData.setGeometry(QtCore.QRect(160, 20, 121, 20))
        self.rbRealTimeData.setObjectName("rbRealTimeData")
        self.btnLoad = QtWidgets.QPushButton(self.groupBox_3)
        self.btnLoad.setGeometry(QtCore.QRect(0, 40, 90, 32))
        self.btnLoad.setObjectName("btnLoad")
        self.btnConn = QtWidgets.QPushButton(self.groupBox_3)
        self.btnConn.setGeometry(QtCore.QRect(100, 40, 90, 32))
        self.btnConn.setObjectName("btnConn")
        self.btnDisconn = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDisconn.setGeometry(QtCore.QRect(200, 40, 90, 32))
        self.btnDisconn.setObjectName("btnDisconn")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(0, 70, 301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 500, 700, 100))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(710, 180, 300, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(710, 390, 301, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(143, 0, 161, 26))
        self.comboBox.setObjectName("comboBox")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionimport = QtWidgets.QAction(MainWindow)
        self.actionimport.setObjectName("actionimport")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZJU Biomedical Signal Analyzer - V0.1"))
        self.groupBox.setTitle(_translate("MainWindow", "Channel Selection"))
        self.checkBox_1.setText(_translate("MainWindow", "channel 01"))
        self.checkBox_2.setText(_translate("MainWindow", "channel 02"))
        self.checkBox_3.setText(_translate("MainWindow", "channel 03"))
        self.checkBox_4.setText(_translate("MainWindow", "channel 04"))
        self.checkBox_5.setText(_translate("MainWindow", "channel 05"))
        self.checkBox_6.setText(_translate("MainWindow", "channel 06"))
        self.checkBox_7.setText(_translate("MainWindow", "channel 07"))
        self.checkBox_8.setText(_translate("MainWindow", "channel 08"))
        self.checkBox_9.setText(_translate("MainWindow", "channel 09"))
        self.checkBox_10.setText(_translate("MainWindow", "channel 10"))
        self.checkBox_11.setText(_translate("MainWindow", "channel 11"))
        self.checkBox_12.setText(_translate("MainWindow", "channel 12"))
        self.checkBox_13.setText(_translate("MainWindow", "channel 13"))
        self.checkBox_14.setText(_translate("MainWindow", "channel 14"))
        self.checkBox_15.setText(_translate("MainWindow", "channel 15"))
        self.checkBox_16.setText(_translate("MainWindow", "channel 16"))
        self.checkBox_17.setText(_translate("MainWindow", "channel 17"))
        self.checkBox_18.setText(_translate("MainWindow", "channel 18"))
        self.checkBox_19.setText(_translate("MainWindow", "channel 19"))
        self.checkBox_20.setText(_translate("MainWindow", "channel 20"))
        self.checkBox_21.setText(_translate("MainWindow", "channel 21"))
        self.checkBox_22.setText(_translate("MainWindow", "channel 22"))
        self.checkBox_23.setText(_translate("MainWindow", "channel 23"))
        self.checkBox_24.setText(_translate("MainWindow", "channel 24"))
        self.checkBox_25.setText(_translate("MainWindow", "channel 25"))
        self.checkBox_26.setText(_translate("MainWindow", "channel 26"))
        self.checkBox_27.setText(_translate("MainWindow", "channel 27"))
        self.checkBox_28.setText(_translate("MainWindow", "channel 28"))
        self.checkBox_29.setText(_translate("MainWindow", "channel 29"))
        self.checkBox_30.setText(_translate("MainWindow", "channel 30"))
        self.checkBox_31.setText(_translate("MainWindow", "channel 31"))
        self.checkBox_32.setText(_translate("MainWindow", "channel 32"))
        self.btnSelectAll.setText(_translate("MainWindow", "Select All"))
        self.btnSelectNone.setText(_translate("MainWindow", "Select None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Setup"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Time Series Plot"))
        self.btnSetTimeSeriesPlot.setText(_translate("MainWindow", "Refresh Plot Setup"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Plot Setup"))
        self.rbDataFromFile.setText(_translate("MainWindow", "Data From File"))
        self.rbRealTimeData.setText(_translate("MainWindow", "Real Time Data"))
        self.btnLoad.setText(_translate("MainWindow", "Load..."))
        self.btnConn.setText(_translate("MainWindow", "Connect"))
        self.btnDisconn.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Extracted Features"))
        self.groupBox_5.setTitle(_translate("MainWindow", "FFT Plot"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Features Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Analyze"))
        self.actionimport.setText(_translate("MainWindow", "import"))

